inspiration2/inspiration2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # http://127.0.0.1:8000/ means localhost
    # if the user visits the http://localhost:8000
    # call the main_app.urls file
    path('', include('main_app.urls')),
    # add accounts
    path('accounts/', include('django.contrib.auth.urls')),
    
]

inspiration2/main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
# ------------------Inspiration----------------------------------------------
    
    # show all the inspirations added
    # http://localhost:8000/inspirations/
    path('inspirations/', views.inspiration_index, name='inspirations_index'),

    # click in to see the details of selected inspiration
    # http://localhost:8000/inspirations/1/
    path('inspirations/<int:inspiration_id>/', views.inspirations_detail, name='detail'),

    # new route used to show a form and create a inspiration.
    # http://localhost:8000/inspirations/create/
    path('inspirations/create/', views.InspirationCreate.as_view(), name='inspirations_create'),

    # update the inspiration 
    # http://localhost:8000/inspirations/1/update/
    path('inspirations/<int:pk>/update/',
        views.InspirationUpdate.as_view(), name='inspirations_update'),

    # delete the inspiration
    # http://localhost:8000/inspirations/1/delete/
    path('inspirations/<int:pk>/delete/',
        views.InspirationDelete.as_view(), name='inspirations_delete'),
    
    # add photo to the inspiration
    path('inspirations/<int:inspiration_id>/add_photo/', views.add_photo, name='add_photo'),

# ------------------Gallery-------------------------------------------------

    # http://localhost:8000/galleries/
    path('galleries/', views.GalleryList.as_view(), name='galleries_index'),

    # http://localhost:8000/galleries/1/
    path('galleries/<int:pk>/', views.galleryDetail, name='galleries_detail'),

    # http://localhost:8000/galleries/create/
    path('galleries/create/', views.GalleryCreate.as_view(), name='galleries_create'),

    # http://localhost:8000/galleries/1/update/
    path('galleries/<int:pk>/update/', views.GalleryUpdate.as_view(), name='galleries_update'),

    # http://localhost:8000/galleries/1/delete/
    path('galleries/<int:pk>/delete/', views.GalleryDelete.as_view(), name='galleries_delete'),

# ------------------Sign up-------------------------------------------------

    # http://localhost:8000/accounts/signup/
    path('accounts/signup/', views.signup, name='signup'),

# ------------------Notes-------------------------------------------------

    # http://localhost:8000/inspiration/2/add_note/
    path('inspirations/<int:inspiration_id>/add_note/', views.add_note, name="add_note"),
]

from .forms import NoteForm

inspiration2/main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date



class Gallery(models.Model):  # IS A
    name = models.CharField(max_length=100)  # HAS A
    description = models.TextField(max_length=250)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name}"

    def get_absolute_url(self):
        return reverse('galleries_detail', kwargs={'pk': self.id})

class Inspiration(models.Model):
    name = models.CharField(max_length=500)
    description = models.CharField(max_length=1000)
    link = models.CharField(max_length=1000)
    galleries = models.ManyToManyField(Gallery)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('inspirations_detail', kwargs={'pk': self.id})
    
class Photo(models.Model):
    url = models.CharField(max_length=400)
    inspiration = models.ForeignKey(Inspiration, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for inspiration_id: {self.inspiration_id} @{self.url}"

class Note(models.Model):
    date = models.DateField()
    note = models.TextField(max_length=1000)
    inspiration = models.ForeignKey(Inspiration, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.note} {self.date}"

    class Meta:
        ordering = ['-date']

inspiration2/main_app/forms.py
from django import forms
from django.forms import ModelForm
from .models import Note
from .models import Inspiration
from .models import Gallery


class CustomMMCF(forms.ModelMultipleChoiceField):
    def label_from_instance(self, gallery):
        return "%s" % gallery.name

class AddGalleriesForm(forms.ModelForm):
    class Meta:
        model = Inspiration
        fields = ['name', 'description', 'link', 'galleries']
        name = forms.CharField(max_length=500)
        description = forms.CharField(max_length=1000)
        link = forms.CharField(max_length=1000)
        galleries = forms.ModelMultipleChoiceField(
        queryset=Gallery.objects.values('name'),
        widget=forms.CheckboxSelectMultiple
        )

class NoteForm(ModelForm):
    class Meta:
        model = Note
        fields = ['date', 'note']

inspiration2/main_app/views.py
import os
import boto3
import uuid

from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse
from .forms import NoteForm, AddGalleriesForm
from django.shortcuts import render, redirect
from .models import Gallery, Inspiration, Note, Photo
from django.http import HttpResponse

from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Import the login_required decorator for functions
from django.contrib.auth.decorators import login_required
# Import the mixin for class-based views
from django.contrib.auth.mixins import LoginRequiredMixin




# Define the home view
def home(request):
    return render(request, "home.html")

# -----------------Notes---------------------------------------------------
@login_required
def add_note(request, inspiration_id):
    form = NoteForm(request.POST)
    if form.is_valid():
        new_note = form.save(commit=False)
        new_note.inspiration_id = inspiration_id
        new_note.save()
    return redirect('detail', inspiration_id=inspiration_id)

# -----------------Inspiration----------------------------------------------


# show all the inspirations in the index page
# http://localhost:8000/inspirations
@login_required
def inspiration_index(request):
    inspirations = Inspiration.objects.filter(user=request.user)
    return render(request, 'inspirations/index.html', {'inspirations': inspirations})

# to see the inspiration detail
# http://localhost:8000/inspirations/1/
@login_required
def inspirations_detail(request, inspiration_id):
    inspiration = Inspiration.objects.get(id=inspiration_id)
    note_form = NoteForm()
    return render(
        request,
        'inspirations/detail.html',
        {'inspiration': inspiration, 'note_form': note_form}
    )

# create inspiration
# http://localhost:8000/inspirations/create/
class InspirationCreate(LoginRequiredMixin,CreateView):
    model = Inspiration

    def post(self,request,*args,**kwargs):
        form = AddGalleriesForm(request.POST)
        if form.is_valid():
            form.instance.user=self.request.user
            form.save()
        return super().form_valid(form)

    fields = ['name', 'description', 'link', 'galleries']

    def form_valid(self, form):
        # self.request.user means current logged in user
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self, **kwargs):
        return reverse('detail', args=(self.object.id,))

# update inspiration 
# http://localhost:8000/inspirations/create/
class InspirationUpdate(LoginRequiredMixin,UpdateView):
    model = Inspiration
    fields = ['description', 'description', 'link']

    def get_success_url(self, **kwargs):
        return reverse('detail', args=(self.object.id,))

class InspirationDelete(LoginRequiredMixin,DeleteView):
    model = Inspiration
    success_url = '/inspirations/'

@login_required
def add_photo(request, inspiration_id):
    # photo-file will be the "name" attribute on the <input type="file">
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        # need a unique "key" for S3 / needs image file extension too
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        # just in case something goes wrong
        try:
            bucket = os.environ['S3_BUCKET']
            s3.upload_fileobj(photo_file, bucket, key)
            # build the full url string
            url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
            # we can assign to inspiration_id or inspiration (if you have a inspiration object)
            Photo.objects.create(url=url, inspiration_id=inspiration_id)
        except:
            print('An error occurred uploading file to S3')
    return redirect('detail', inspiration_id=inspiration_id)

# -----------------Gallery---------------------------------------------------

# http://localhost:8000/galleries/
class GalleryList(LoginRequiredMixin,ListView):
    model = Gallery
    def get_queryset(self):
        return Gallery.objects.filter(user=self.request.user)
    
@login_required        
def galleryDetail(request, pk):
    gallery = Gallery.objects.get(id = pk)
    inspirations = Inspiration.objects.filter(galleries__id = pk)
    return render(request, 'galleries/detail.html', {'inspirations': inspirations, 'gallery': gallery})
        
# http://localhost:8000/galleries/create/
class GalleryCreate(LoginRequiredMixin,CreateView):
    model = Gallery
    fields = ['name', 'description']
    def form_valid(self, form):
        # Assign the logged in user (self.request.user)
        form.instance.user = self.request.user 
        # Let the CreateView do its job as usual
        return super().form_valid(form)

# http://localhost:8000/galleries/1/update/
class GalleryUpdate(LoginRequiredMixin,UpdateView):
    model = Gallery
    fields = fields = '__all__'
    
# http://localhost:8000/galleries/1/delete/
class GalleryDelete(LoginRequiredMixin,DeleteView):
    model = Gallery
    success_url = '/galleries/'

def some_function(request):
    secret_key = os.environ['SECRET_KEY']
    
def signup(request):
  error_message = ''
  if request.method == 'POST':
    # This is how to create a 'user' form object
    # that includes the data from the browser
    form = UserCreationForm(request.POST)
    if form.is_valid():
      # This will add the user to the database
      user = form.save()
      # This is how we log a user in via code
      login(request, user)
      return redirect('/galleries/')
    else:
      error_message = 'Invalid sign up - try again'
      
  # A bad POST or a GET request, so render signup.html with an empty form
  form = UserCreationForm() # this is our html form
  context = {'form': form, 
             'error_message': error_message
            }
  return render(request, 'registration/signup.html', context)

inspiration2/main_app/templates/inspirations/detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h1 class="my-header">Inspiration Details</h1>
    <hr class="mt-2">
    <br>
    <div class="insp-container">
        <div class="new-container">
            {% for photo in inspiration.photo_set.all %}
                <img src="{{photo.url}}" class="cont-image" alt="no image uploaded yet!">
            {% endfor %}
            <div class="insp-body">
                <h5>{{ inspiration.name }}</h5>
                <div>{{ inspiration.description }}</div>
                <a href="{{ inspiration.link }}" style="font-size: 14px; color: #f39c12;">{{ inspiration.link }}</a>
            </div>
        </div>
    </div>
    {% for photo in inspiration.photo_set.all %}

    {% empty %}
        <div class="card-panel teal-text center-align">Upload photo below</div>
        <br>
        <form action="{% url 'add_photo' inspiration.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
            {% csrf_token %}
            <input type="file" name="photo-file">
            <br><br>
            <input type="submit" class="btn cancel_btn" value="Upload Photo">
        </form>
    {% endfor %}
    <br>
    <hr>
    <div class="note-container">
        <form action="{% url 'add_note' inspiration.id %}" method="POST">
            {% csrf_token %}
            {{ note_form.as_p }}
            <input type="submit" class="btn cancel_btn" value="Add Note">
        </form>
    </div>
    <br>
    <br>
    {% for note in inspiration.note_set.all %}
        {{ note.date }}
        {{ note.note }}

    {% empty %}
        <div>No Notes yet </div>
    {% endfor %}

    <hr class="mt-2">

    <a href="{% url 'inspirations_update' inspiration.id %}">
        <button class="btn cancel_btn" >Edit Inspiration</button>
    </a>
    <br>
    <br>
    <a href="{% url 'inspirations_delete' inspiration.id %}">
        <button class="btn login_btn">Delete Inspiration</button>
    </a>
    <br>
</div>

{% endblock %}

inspiration2/main_app/templates/inspirations/index.html
{% extends 'base.html' %}
{% block content %}

<h1 class="fw-light text-center">My Inspirations</h1>
<hr class="mt-2">

<div class="container">
    <div class="row text-center text-lg-start">
    {% for inspiration in inspirations %}
        {% for photo in inspiration.photo_set.all %}
            <div class="col-lg-3 col-md-4 col-6">
                <a href="{% url 'detail' inspiration.id %}" class="d-block mb-4 h-100">
                    <img class="img-fluid rounded mx-auto d-block" src="{{photo.url}}" alt="">
                </a>
            </div>
        {% empty %}
            <div class="col-lg-3 col-md-4 col-6">
                <a href="{% url 'detail' inspiration.id %}" class="d-block mb-4 h-100">
                    <img class="img-fluid rounded mx-auto d-block" src="https://i.imgur.com/OA95w1G.png" alt="">
                </a>
            </div>
            {% endfor %}
    {% endfor %}
    </div>
</div>
{% endblock %}